from fastapi import APIRouter, Body, Query, HTTPException
from .. import db, search, logistics
from ..config import CATALOG_ROOT_ID

router = APIRouter(prefix="/api", tags=["catalog"])

MISS_MIGRATION = """
CREATE TABLE IF NOT EXISTS search_misses (
  q       text PRIMARY KEY,
  misses  int DEFAULT 1,
  last_at timestamptz DEFAULT now()
);
"""


async def ensure_misses():
    async with db.pool.connection() as conn:
        await conn.execute(MISS_MIGRATION)


# Перенос legacy-функционала: второй тип связи товар↔товар + подписки на поступление.
# Схема db/schema.sql применяется только при init БД, поэтому для уже поднятого
# прода миграция догоняется на старте API (как в prices/quotes/settings).
# Критическая часть: без relation_type запросы карточки не выполнятся, поэтому она
# идёт отдельным вызовом — чтобы сбой необязательной части её НЕ откатил.
RELATIONS_MIGRATION_CORE = """
-- Тип связи: analog (legacy it_b_aarts) | install_option (legacy it_b_aarts2).
-- Дефолт 'analog' — существующие строки и блок «Аналоги» ведут себя ровно как раньше.
ALTER TABLE analogs ADD COLUMN IF NOT EXISTS relation_type text NOT NULL DEFAULT 'analog';

CREATE TABLE IF NOT EXISTS stock_alerts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint REFERENCES products(id) ON DELETE CASCADE,
  email       text NOT NULL,
  name        text,
  phone       text,
  notified_at timestamptz,
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_stock_alerts_pending
  ON stock_alerts(product_id) WHERE notified_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_stock_alerts_active
  ON stock_alerts(product_id, lower(email)) WHERE notified_at IS NULL;
"""

# Необязательная часть: ускорение и защита от дублей. Если тут что-то не сложится
# (напр. дедуп на большой таблице), карточка всё равно работает.
RELATIONS_MIGRATION_OPT = """
-- До этой миграции уникальности на analogs не было, и повторный прогон ETL мог
-- насажать дублей — снимаем их, иначе CREATE UNIQUE INDEX упадёт.
DELETE FROM analogs a USING analogs b
 WHERE a.id > b.id
   AND a.product_id = b.product_id
   AND a.relation_type = b.relation_type
   AND a.normalized_article IS NOT NULL
   AND a.normalized_article = b.normalized_article;

CREATE UNIQUE INDEX IF NOT EXISTS ux_analogs_uniq
  ON analogs(product_id, normalized_article, relation_type)
  WHERE normalized_article IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_analogs_rel ON analogs(product_id, relation_type);
"""


async def ensure_relations():
    async with db.pool.connection() as conn:
        await conn.execute(RELATIONS_MIGRATION_CORE)
    try:
        async with db.pool.connection() as conn:
            await conn.execute(RELATIONS_MIGRATION_OPT)
    except Exception as e:
        # Не валим старт: без уникального индекса ETL просто может насажать дублей,
        # но витрина и подписки работают.
        print("analogs dedup/index warning:", e)

# Разрешённые сортировки витрины (защита от инъекций в ORDER BY).
_SORTS = {
    # По умолчанию — по ПОЗИЦИИ на схеме (узлы каталога), а без позиций — по алфавиту.
    "default":    "(position_num IS NULL), position_num ASC, name ASC",
    "price_asc":  "(min_price IS NULL), min_price ASC, name",
    "price_desc": "min_price DESC NULLS LAST, name",
    "stock":      "in_stock DESC NULLS LAST, (min_price IS NULL), min_price ASC",
    "name":       "name ASC",
}

# Товары, привязанные НЕПОСРЕДСТВЕННО к категории (для drill-down по узлам).
# Дерево навигируется группами-плитками, а карточки показываются на своём уровне.
# Поиск ВНУТРИ группы: товары всего поддерева, отфильтрованные по артикулу/названию.
_SUBTREE_SEARCH = """
  WITH agg AS (
    SELECT p.id, p.manufacturer_article, p.name, p.brand, p.primary_image,
           NULL::text AS position, NULL::int AS position_num,
           MIN(o.price) FILTER (WHERE o.price IS NOT NULL) AS min_price,
           BOOL_OR(o.in_stock) AS in_stock,
           (SELECT MIN(s.delivery_days) FROM offers o2 JOIN suppliers s ON s.id=o2.supplier_id
              WHERE o2.product_id=p.id AND o2.source='price') AS eta_days
    FROM categories d
    JOIN product_categories pc ON pc.category_id = d.id
    JOIN products p ON p.id = pc.product_id
    LEFT JOIN offers o ON o.product_id = p.id
    WHERE (d.path = %(path)s OR d.path LIKE %(path)s || '/%%')
      AND p.visible
      AND (p.manufacturer_article ILIKE %(q)s OR p.name ILIKE %(q)s OR p.brand ILIKE %(q)s)
    GROUP BY p.id
  )
"""

_DIRECT_AGG = """
  WITH agg AS (
    SELECT p.id, p.manufacturer_article, p.name, p.brand, p.primary_image,
           MAX(pc.position) AS position,
           MAX(nullif(regexp_replace(coalesce(pc.position,''), '[^0-9]', '', 'g'), '')::int) AS position_num,
           MIN(o.price) FILTER (WHERE o.price IS NOT NULL) AS min_price,
           BOOL_OR(o.in_stock) AS in_stock,
           (SELECT MIN(s.delivery_days) FROM offers o2 JOIN suppliers s ON s.id=o2.supplier_id
              WHERE o2.product_id=p.id AND o2.source='price') AS eta_days
    FROM product_categories pc
    JOIN products p ON p.id = pc.product_id
    LEFT JOIN offers o ON o.product_id = p.id
    WHERE pc.category_id = %(cat)s AND p.visible
    GROUP BY p.id
  )
"""


# Строки блока связей карточки. Один запрос на оба типа (%(rel)s): аналоги и
# варианты установки различаются только relation_type, вывод у них одинаковый.
_RELATION_ROWS = """
  SELECT DISTINCT ON (a.normalized_article)
         a.analog_article, a.linked_product_id,
         COALESCE(lp.name, a.analog_name) AS analog_name,
         lp.brand AS brand,
         (SELECT c.name FROM product_categories pc JOIN categories c ON c.id=pc.category_id
            WHERE pc.product_id=a.linked_product_id
            ORDER BY c.level DESC LIMIT 1) AS group_name,
         (SELECT MIN(price) FROM offers o
            WHERE o.product_id=a.linked_product_id AND o.price IS NOT NULL) AS min_price,
         (SELECT BOOL_OR(in_stock) FROM offers o
            WHERE o.product_id=a.linked_product_id) AS in_stock,
         (SELECT MIN(s.delivery_days) FROM offers o JOIN suppliers s ON s.id=o.supplier_id
            WHERE o.product_id=a.linked_product_id AND o.source='price') AS eta_days
  FROM analogs a
  LEFT JOIN products lp ON lp.id = a.linked_product_id
  WHERE a.product_id = %(pid)s
    AND a.relation_type = %(rel)s
    AND a.linked_product_id IS DISTINCT FROM %(pid)s
    AND a.normalized_article IS DISTINCT FROM
        (SELECT normalized_article FROM products WHERE id = %(pid)s)
  ORDER BY a.normalized_article, a.linked_product_id NULLS LAST
"""


@router.get("/search")
async def search_catalog(
    q: str = Query(..., min_length=1, description="артикул, аналог или название"),
    limit: int = Query(20, le=100),
    offset: int = 0,
    in_stock: bool | None = None,
):
    """Мгновенный поиск по артикулу/аналогу/названию через Meilisearch."""
    res = search.search(q, limit=limit, offset=offset, in_stock=in_stock)
    total = res.get("estimatedTotalHits")
    # Лог «ничего не найдено» — только по РЕАЛЬНОМУ поиску (limit>=20), не по автодополнению.
    if not total and offset == 0 and limit >= 20 and q and len(q.strip()) >= 2:
        try:
            await db.fetchone(
                """INSERT INTO search_misses (q, misses, last_at) VALUES (%s, 1, now())
                   ON CONFLICT (q) DO UPDATE SET misses = search_misses.misses + 1, last_at = now()
                   RETURNING q""", (q.strip().lower(),))
        except Exception as e:
            print("search miss log failed:", e)
    return {"query": q, "total": total, "hits": res.get("hits", [])}


@router.post("/quick-resolve")
async def quick_resolve(body: dict = Body(...)):
    """Быстрый заказ списком: строки «АРТИКУЛ [кол-во]» → товары с ценой/наличием.
    Матч по норм-артикулу (точный + через аналоги). Найденные/ненайденные раздельно."""
    lines = body.get("lines") or (body.get("text") or "").splitlines()
    out = []
    for raw in lines[:200]:
        s = (raw or "").strip()
        if not s:
            continue
        parts = s.split()
        qty, art = 1, s
        if len(parts) > 1 and parts[-1].replace(",", ".").replace(".", "", 1).isdigit():
            try:
                qty = max(1, int(float(parts[-1].replace(",", "."))))
                art = " ".join(parts[:-1])
            except ValueError:
                pass
        sql = """SELECT p.id, p.manufacturer_article, p.name, p.brand,
                        (SELECT MIN(o.price) FROM offers o WHERE o.product_id=p.id AND o.price IS NOT NULL) AS price,
                        (SELECT BOOL_OR(o.in_stock) FROM offers o WHERE o.product_id=p.id) AS in_stock
                 FROM products p {join} WHERE p.visible AND {cond}=norm_article(%s)
                 ORDER BY p.id LIMIT 1"""
        row = await db.fetchone(sql.format(join="", cond="p.normalized_article"), (art,))
        if not row:
            # Только настоящие аналоги: вариант установки — не замена, подставлять
            # его в быстрый заказ вместо запрошенного артикула нельзя.
            row = await db.fetchone(
                sql.format(join="JOIN analogs a ON a.product_id=p.id AND a.relation_type='analog'",
                           cond="a.normalized_article"), (art,))
        if row:
            row["price"] = float(row["price"]) if row["price"] is not None else None
            out.append({"input": art, "qty": qty, "matched": True, **row})
        else:
            out.append({"input": art, "qty": qty, "matched": False})
    return {"items": out, "found": sum(1 for i in out if i["matched"]),
            "missing": sum(1 for i in out if not i["matched"])}


@router.get("/sitemap")
async def sitemap_data():
    """Данные для sitemap.xml: id видимых товаров (+updated) и категорий каталога."""
    prods = await db.fetch(
        "SELECT id, extract(epoch FROM updated_at)::bigint AS ts FROM products WHERE visible ORDER BY id")
    cats = await db.fetch("SELECT id FROM categories WHERE visible ORDER BY id")
    return {"products": prods, "categories": [c["id"] for c in cats]}


@router.get("/products/{product_id}")
async def get_product(product_id: int):
    p = await db.fetchone("SELECT * FROM products WHERE id=%s AND visible", (product_id,))
    if not p:
        raise HTTPException(404, "product not found")
    p["images"] = await db.fetch(
        "SELECT url, sort FROM product_images WHERE product_id=%s ORDER BY sort", (product_id,))
    # В каталоге НЕ раскрываем поставщика — только цену, наличие и срок поставки
    # (срок фиксируется в карточке поставщика: delivery_days / delivery_note).
    p["offers"] = await db.fetch(
        """SELECT o.id, o.article, o.price, o.qty, o.in_stock,
                  s.delivery_days, s.delivery_note
           FROM offers o LEFT JOIN suppliers s ON s.id=o.supplier_id
           WHERE o.product_id=%s ORDER BY o.price NULLS LAST""", (product_id,))
    # Связи товар↔товар + (если у связи есть карточка) её цена, наличие и срок.
    # ИСКЛЮЧАЕМ саму карточку (self-link и совпадение артикула) и дубли (по норм. артикулу).
    p["analogs"] = await db.fetch(_RELATION_ROWS, {"pid": product_id, "rel": "analog"})
    # «Возможные варианты установки» — legacy it_b_aarts2 (catalog.php:550, блок duplicates2).
    # Это НЕ прямая замена: деталь встаёт как вариант, но требует сверки — поэтому
    # отдельный блок, а не подмешивание в аналоги.
    p["install_options"] = await db.fetch(
        _RELATION_ROWS, {"pid": product_id, "rel": "install_option"})
    # Детали, стоящие на ТОЙ ЖЕ позиции схемы узла (напр. полуось левая/правая,
    # исполнения разных производителей). Это НЕ аналоги (левая≠правая), поэтому
    # отдаём отдельным блоком position_variants с ценой/наличием/сроком.
    siblings = await db.fetch(
        """SELECT DISTINCT ON (p2.id)
                  p2.manufacturer_article AS analog_article, p2.id AS linked_product_id,
                  p2.name AS analog_name, p2.brand AS brand,
                  (SELECT c.name FROM product_categories pc2 JOIN categories c ON c.id=pc2.category_id
                     WHERE pc2.product_id=p2.id ORDER BY c.level DESC LIMIT 1) AS group_name,
                  (SELECT MIN(price) FROM offers o
                     WHERE o.product_id=p2.id AND o.price IS NOT NULL) AS min_price,
                  (SELECT BOOL_OR(in_stock) FROM offers o WHERE o.product_id=p2.id) AS in_stock,
                  (SELECT MIN(s.delivery_days) FROM offers o JOIN suppliers s ON s.id=o.supplier_id
                     WHERE o.product_id=p2.id AND o.source='price') AS eta_days
           FROM product_categories pcs
           JOIN categories cc ON cc.id=pcs.category_id AND cc.path LIKE %(root)s
           JOIN product_categories pc2
                ON pc2.category_id=pcs.category_id AND pc2.position=pcs.position
               AND pc2.product_id<>pcs.product_id
           JOIN products p2 ON p2.id=pc2.product_id AND p2.visible
           WHERE pcs.product_id=%(pid)s AND coalesce(pcs.position,'') <> ''
           ORDER BY p2.id
           LIMIT 100""",
        {"pid": product_id, "root": f"%/{CATALOG_ROOT_ID}/%"})
    # Не дублируем детали, которые уже перечислены как аналоги или варианты установки.
    related_ids = {a["linked_product_id"]
                   for a in (*p["analogs"], *p["install_options"])
                   if a["linked_product_id"] is not None}
    p["position_variants"] = [s for s in siblings if s["linked_product_id"] not in related_ids]
    for a in (*p["analogs"], *p["install_options"], *p["position_variants"]):
        a["min_price"] = float(a["min_price"]) if a["min_price"] is not None else None

    # Предложения по аналогам в списке покупки (legacy catalog.php:350-371): если у
    # товара НЕТ своих предложений, показываем предложения его аналогов — карточка
    # без прайса всё равно даёт клиенту что купить. Отдаём ОТДЕЛЬНЫМ полем, чтобы
    # p["offers"] и все его текущие потребители остались нетронутыми. Поля via_* нужны
    # фронту, чтобы положить в корзину ИМЕННО аналог, а не пустой текущий товар.
    p["offers_via_analogs"] = [] if p["offers"] else await db.fetch(
        """SELECT DISTINCT ON (o.price, lp.id)
                  o.id, o.article, o.price, o.qty, o.in_stock,
                  s.delivery_days, s.delivery_note,
                  lp.id AS via_product_id, lp.manufacturer_article AS via_article,
                  lp.name AS via_name
           FROM analogs a
           JOIN products lp ON lp.id = a.linked_product_id AND lp.visible
           JOIN offers o ON o.product_id = lp.id
           LEFT JOIN suppliers s ON s.id = o.supplier_id
           WHERE a.product_id = %(pid)s
             AND a.relation_type = 'analog'
             AND a.linked_product_id IS DISTINCT FROM %(pid)s
           ORDER BY o.price NULLS LAST, lp.id
           LIMIT 20""",
        {"pid": product_id})

    # «от N ₽» по всей группе взаимозаменяемости (legacy catalog.php:478-488): минимум
    # по товару ВМЕСТЕ с его аналогами. Отдельным полем — min_price витрины и сортировка
    # каталога по-прежнему считаются по собственным offers товара, цифры там не поедут.
    grp = await db.fetchone(
        """SELECT MIN(o.price) AS price FROM offers o
           WHERE o.price IS NOT NULL
             AND (o.product_id = %(pid)s
                  OR o.product_id IN (SELECT a.linked_product_id FROM analogs a
                                       WHERE a.product_id = %(pid)s
                                         AND a.relation_type = 'analog'
                                         AND a.linked_product_id IS NOT NULL))""",
        {"pid": product_id})
    p["group_min_price"] = float(grp["price"]) if grp and grp["price"] is not None else None
    cats = await db.fetch(
        """SELECT c.id, c.name, c.path, c.image, pc.position, pc.sort
           FROM categories c
           JOIN product_categories pc ON pc.category_id=c.id
           WHERE pc.product_id=%s
           ORDER BY pc.sort, c.name""", (product_id,))
    p["categories"] = cats

    # Применимость: для каждой схемы строим хлебную тропу от корня витрины
    # (модель → узел → подгруппа) + позиция детали на схеме.
    all_ids = {int(x) for c in cats for x in (c["path"] or "").strip("/").split("/") if x}
    names = {}
    if all_ids:
        for r in await db.fetch("SELECT id, name FROM categories WHERE id = ANY(%s)", (list(all_ids),)):
            names[r["id"]] = r["name"]
    applicability = []
    for c in cats:
        ids = [int(x) for x in (c["path"] or "").strip("/").split("/") if x]
        trail, seen = [], False
        for cid in ids:
            if cid == CATALOG_ROOT_ID:
                seen = True
                continue
            if seen and cid in names:
                trail.append({"id": cid, "name": names[cid]})
        applicability.append({
            "category_id": c["id"],
            "name": c["name"],
            "position": c["position"],
            "scheme_image": c["image"],     # изображение схемы узла (если есть)
            "trail": trail,
        })
    # Схемы узлов, где у детали есть позиция (для блока «Схема узла» в карточке).
    # Берём из ПОЛНОГО набора — до фильтрации применимости.
    p["schemes"] = [a for a in applicability if a["scheme_image"]]

    # Применимость для показа: убираем «пустые строки» (записи вне дерева витрины,
    # напр. свалка «ЗАПЧАСТИ» id 451 — её путь не содержит корень каталога → trail пуст)
    # и дубли (одинаковая хлебная тропа); при совпадении оставляем запись с позицией/схемой.
    clean, seen_sig = [], {}
    for a in applicability:
        if not a["trail"]:
            continue
        sig = tuple(t["id"] for t in a["trail"])
        prev = seen_sig.get(sig)
        if prev is None:
            seen_sig[sig] = len(clean)
            clean.append(a)
        elif (a["position"] or a["scheme_image"]) and not (clean[prev]["position"] or clean[prev]["scheme_image"]):
            clean[prev] = a       # предпочитаем более информативную запись
    p["applicability"] = clean
    return p


@router.get("/products/by-article/{article}")
async def get_by_article(article: str):
    """Точный подбор по артикулу производителя (нормализованный) + через аналоги."""
    rows = await db.fetch(
        """SELECT id, manufacturer_article, name, brand, slug, primary_image, 'exact' AS match
           FROM products WHERE normalized_article = norm_article(%s) AND visible
           UNION
           SELECT p.id, p.manufacturer_article, p.name, p.brand, p.slug, p.primary_image, 'analog'
           FROM products p JOIN analogs a ON a.product_id=p.id
           WHERE a.normalized_article = norm_article(%s) AND p.visible
             AND a.relation_type = 'analog'""",
        (article, article))
    return {"article": article, "results": rows}


@router.get("/products/{product_id}/eta")
async def product_eta(product_id: int, city: str | None = Query(None, description="город клиента")):
    """Срок доставки товара: в наличии → отгрузка; под заказ → пополнение + отгрузка."""
    o = await db.fetchone(
        """SELECT o.in_stock, s.city AS supplier_city
           FROM offers o LEFT JOIN suppliers s ON s.id=o.supplier_id
           WHERE o.product_id=%s ORDER BY o.in_stock DESC, o.price ASC NULLS LAST LIMIT 1""",
        (product_id,))
    if not o:
        return {"product_id": product_id, "note": "нет предложений — срок уточняется"}
    return {"product_id": product_id,
            **logistics.estimate(bool(o["in_stock"]), o["supplier_city"], city)}


@router.post("/products/{product_id}/stock-alert")
async def create_stock_alert(product_id: int, body: dict = Body(...)):
    """Подписка «сообщить о поступлении» (перенос legacy it_b_notify).

    Письмо отправляет воркер, когда по товару появится offer с in_stock.
    Повторная подписка тем же email просто обновляет контакты — дубля не будет.
    """
    email = (body.get("email") or "").strip()
    if len(email) < 5 or "@" not in email or "." not in email.split("@")[-1]:
        raise HTTPException(422, "укажите корректный email")
    prod = await db.fetchone("SELECT id FROM products WHERE id=%s AND visible", (product_id,))
    if not prod:
        raise HTTPException(404, "product not found")
    await db.fetchone(
        """INSERT INTO stock_alerts (product_id, email, name, phone)
           VALUES (%s, %s, %s, %s)
           ON CONFLICT (product_id, lower(email)) WHERE notified_at IS NULL
           DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone
           RETURNING id""",
        (product_id, email, (body.get("name") or "").strip() or None,
         (body.get("phone") or "").strip() or None))
    return {"ok": True}


@router.get("/categories")
async def list_categories(parent_id: int | None = None):
    if parent_id is None:
        rows = await db.fetch(
            "SELECT id, name, slug, level, image FROM categories WHERE parent_id IS NULL AND visible ORDER BY sort")
    else:
        rows = await db.fetch(
            "SELECT id, name, slug, level, image FROM categories WHERE parent_id=%s AND visible ORDER BY sort",
            (parent_id,))
    return rows


# --- Витринный каталог: просмотр по маркам техники и узлам ------------------

async def _children(parent_id: int, include_hidden: bool = False):
    """Подкатегории с числом товаров в поддереве (по материализованному пути).
    В drill-down (include_hidden=True) показываем узлы с товарами даже если visible=false
    (в legacy у части узлов флаг сброшен, иначе модель выглядит пустой)."""
    return await db.fetch(
        """SELECT id, name, slug, image, product_count FROM (
             SELECT c.id, c.name, c.slug, c.image, c.sort, c.visible,
                    (SELECT count(DISTINCT pc.product_id)
                       FROM categories d JOIN product_categories pc ON pc.category_id = d.id
                       WHERE d.path = c.path OR d.path LIKE c.path || '/%%') AS product_count
             FROM categories c WHERE c.parent_id = %s
           ) t
           WHERE product_count > 0 AND (visible OR %s)
           ORDER BY product_count DESC, sort""",
        (parent_id, include_hidden))


def _classify(name: str) -> str:
    """Раскладываем корневые узлы на смысловые секции витрины."""
    n = (name or "").strip().lower()
    if n.startswith("двигатель") or n.startswith("двс"):
        return "engines"
    if n.endswith("запчасти") or "фильтр" in n or "форсунк" in n or n in ("инструмент",):
        return "brands"
    return "models"


@router.get("/catalog/roots")
async def catalog_roots():
    """Верхний уровень витрины: модели техники, двигатели и каталоги производителей."""
    rows = await _children(CATALOG_ROOT_ID)
    items = [r for r in rows if r["product_count"]]  # только узлы с товарами
    for r in items:
        r["group"] = _classify(r["name"])
    return {"root_id": CATALOG_ROOT_ID, "items": items}


@router.get("/catalog/browse")
async def catalog_browse(
    category: int = Query(..., description="id категории для просмотра"),
    sort: str = Query("default"),
    stock: bool = Query(False, description="только в наличии"),
    q: str | None = Query(None, description="поиск внутри группы (по поддереву)"),
    page: int = Query(1, ge=1),
    per_page: int = Query(24, ge=1, le=96),
):
    """Товары внутри категории (по всему поддереву) + подкатегории + хлебные крошки.
    q — поиск по артикулу/названию ВНУТРИ текущей группы (всё поддерево)."""
    # без AND visible: в legacy у части узлов флаг сброшен, но товары есть — их нужно открывать
    cat = await db.fetchone(
        "SELECT id, name, slug, path, level, image FROM categories WHERE id=%s", (category,))
    if not cat:
        raise HTTPException(404, "category not found")

    order = _SORTS.get(sort, _SORTS["default"])
    having = "WHERE in_stock" if stock else ""
    params = {"cat": category, "limit": per_page, "offset": (page - 1) * per_page}
    q = (q or "").strip()
    if q:
        agg, params["path"], params["q"] = _SUBTREE_SEARCH, cat["path"], f"%{q}%"
    else:
        agg = _DIRECT_AGG

    total_row = await db.fetchone(
        f"{agg} SELECT count(*) AS n FROM agg {having}", params)
    products = await db.fetch(
        f"{agg} SELECT * FROM agg {having} ORDER BY {order} LIMIT %(limit)s OFFSET %(offset)s",
        params)

    # хлебные крошки из материализованного пути, начиная от корня витрины
    path_ids = [int(x) for x in cat["path"].strip("/").split("/") if x]
    crumbs = []
    if path_ids:
        rows = await db.fetch(
            "SELECT id, name FROM categories WHERE id = ANY(%s)", (path_ids,))
        by_id = {r["id"]: r["name"] for r in rows}
        seen = False
        for cid in path_ids:
            if cid == CATALOG_ROOT_ID:
                seen = True
            if seen and cid in by_id:
                crumbs.append({"id": cid, "name": by_id[cid]})

    for p in products:
        p["min_price"] = float(p["min_price"]) if p["min_price"] is not None else None

    return {
        "category": {"id": cat["id"], "name": cat["name"], "path": cat["path"], "image": cat["image"]},
        "breadcrumbs": crumbs,
        "children": await _children(category, include_hidden=True),
        "total": total_row["n"],
        "page": page,
        "per_page": per_page,
        "products": products,
    }
