-- ============================================================================
-- specinter — доменная схема нового портала (PostgreSQL)
-- Ядро: каталог, аналоги, поставщики, прайсы, клиенты, заказы (стабы), метаданные ETL.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;      -- нечёткий поиск по артикулу
CREATE EXTENSION IF NOT EXISTS unaccent;

-- --- Нормализация артикула: единый ключ подбора -----------------------------
-- Убираем регистр, пробелы и разделители, чтобы "16Y-01 00005" == "16y0100005".
CREATE OR REPLACE FUNCTION norm_article(txt text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT nullif(regexp_replace(lower(coalesce(txt,'')), '[^a-z0-9а-я]', '', 'g'), '')
$$;

-- ============================================================================
-- Каталог
-- ============================================================================

-- Дерево категорий (из it_tree). Материализованный путь для простоты.
CREATE TABLE categories (
  id           bigint PRIMARY KEY,
  parent_id    bigint REFERENCES categories(id) ON DELETE CASCADE,
  legacy_id    bigint UNIQUE,               -- it_tree.id
  name         text NOT NULL,
  slug         text,
  path         text,                        -- materialized path: /40/65/66
  image        text,                        -- главное фото категории (из it_c_catalog.img)
  level        int  NOT NULL DEFAULT 0,
  sort         bigint DEFAULT 0,
  visible      boolean NOT NULL DEFAULT true
);
CREATE INDEX ix_categories_parent ON categories(parent_id);

-- Товар = карточка-артикул (из it_b_catitem)
CREATE TABLE products (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id            bigint UNIQUE,        -- it_b_catitem.id
  manufacturer_article text,                -- art
  normalized_article   text GENERATED ALWAYS AS (norm_article(manufacturer_article)) STORED,
  name                 text,                -- name_rus
  name_en              text,                -- name_eng
  brand                text,
  description_html     text,                -- html / d_html
  seo_title            text,
  seo_description      text,
  seo_keywords         text,
  slug                 text,                -- uurl
  primary_image        text,               -- img
  visible              boolean NOT NULL DEFAULT true,
  created_at           timestamptz DEFAULT now(),
  updated_at           timestamptz DEFAULT now()
);
CREATE INDEX ix_products_norm_art      ON products(normalized_article);
CREATE INDEX ix_products_art_trgm      ON products USING gin (manufacturer_article gin_trgm_ops);
CREATE INDEX ix_products_name_trgm     ON products USING gin (name gin_trgm_ops);

-- Изображения товара (из it_b_goodimage / img_1..img_4 / images)
CREATE TABLE product_images (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint REFERENCES products(id) ON DELETE CASCADE,
  url         text NOT NULL,
  sort        int DEFAULT 0
);
CREATE INDEX ix_product_images_product ON product_images(product_id);

-- Связь товар↔категория = применимость (из it_b_ablock).
-- position — «позиция на схеме» (it_b_ablock.num), sort — порядок в узле.
CREATE TABLE product_categories (
  product_id  bigint REFERENCES products(id) ON DELETE CASCADE,
  category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
  position    text,
  sort        int DEFAULT 0,
  PRIMARY KEY (product_id, category_id)
);

-- Аналоги / кросс-номера (из it_b_aarts) и варианты установки (из it_b_aarts2).
-- Ценный актив для подбора: это ручная экспертная разметка, алгоритмом не воспроизводится.
--
-- relation_type разделяет ДВА разных смысла, которые в legacy жили в разных таблицах
-- и выводились разными блоками карточки:
--   'analog'         — взаимозаменяемо (legacy it_b_aarts, блок «Предложения по аналогам»);
--   'install_option' — «встанет как вариант установки», НЕ прямая замена
--                      (legacy it_b_aarts2, блок «Возможные варианты установки»).
-- Дефолт 'analog' — чтобы существующие строки и запросы вели себя как раньше.
CREATE TABLE analogs (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id         bigint REFERENCES products(id) ON DELETE CASCADE,  -- владелец (blockparent)
  analog_article     text NOT NULL,
  normalized_article text GENERATED ALWAYS AS (norm_article(analog_article)) STORED,
  analog_name        text,
  linked_product_id  bigint REFERENCES products(id) ON DELETE SET NULL, -- good_id_arts, если есть карточка
  relation_type      text NOT NULL DEFAULT 'analog'
                     CHECK (relation_type IN ('analog','install_option')),
  source             text DEFAULT 'legacy'
);
CREATE INDEX ix_analogs_norm_art ON analogs(normalized_article);
CREATE INDEX ix_analogs_product  ON analogs(product_id);
CREATE INDEX ix_analogs_rel      ON analogs(product_id, relation_type);
-- Защита от дублей при повторном прогоне ETL (в legacy уникальности не было).
CREATE UNIQUE INDEX ux_analogs_uniq
  ON analogs(product_id, normalized_article, relation_type)
  WHERE normalized_article IS NOT NULL;

-- ============================================================================
-- Поставщики и прайсы
-- ============================================================================

CREATE TABLE suppliers (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  sender_email   text,                       -- адрес, с которого приходят прайсы
  city           text,                        -- для расчёта срока пополнения
  delivery_days  int,                         -- срок поставки от поставщика (раб. дней), фикс в карточке
  delivery_note  text,                        -- пояснение к сроку (напр. «под заказ 2 нед.»)
  markup_percent numeric(6,2) DEFAULT 15.00,  -- наценка по умолчанию
  price_round    numeric(10,2) DEFAULT 0.5,   -- округление цены вверх
  active         boolean NOT NULL DEFAULT true,
  created_at     timestamptz DEFAULT now()
);

-- Профиль парсинга XLSX для поставщика (маппинг колонок и шапки)
CREATE TABLE supplier_price_profiles (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id    bigint REFERENCES suppliers(id) ON DELETE CASCADE,
  auto           boolean DEFAULT true,        -- true = автоопределение колонок (по умолчанию)
  sheet_index    int DEFAULT 0,
  header_rows    int DEFAULT 7,               -- сколько строк пропустить сверху (при auto=false)
  col_maker      int, col_name int, col_article int,
  col_price      int, col_qty int, col_code int, col_cross int,
  currency       text DEFAULT 'RUB'
);

-- Строки прайса с историей (НЕ TRUNCATE, в отличие от legacy)
CREATE TABLE supplier_prices (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id        bigint REFERENCES suppliers(id) ON DELETE CASCADE,
  article            text,
  normalized_article text GENERATED ALWAYS AS (norm_article(article)) STORED,
  external_code      text,                    -- код 1С (xlsx_id) — для совместимости
  name               text,
  maker              text,
  cross_numbers      text,                    -- кросс-номера из прайса (для матчинга)
  price              numeric(14,2),
  qty                numeric(14,3),
  matched_product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  match_method       text,                    -- exact_article | analog | fuzzy | code_1c | none
  match_confidence   numeric(4,3),
  received_at        timestamptz DEFAULT now()
);
CREATE INDEX ix_sp_norm_art     ON supplier_prices(normalized_article);
CREATE INDEX ix_sp_supplier     ON supplier_prices(supplier_id);
CREATE INDEX ix_sp_matched      ON supplier_prices(matched_product_id);

-- Витринное предложение (из it_b_variant + расчёт лучшего прайса)
CREATE TABLE offers (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id    bigint UNIQUE,                -- it_b_variant.id
  product_id   bigint REFERENCES products(id) ON DELETE CASCADE,
  supplier_id  bigint REFERENCES suppliers(id) ON DELETE SET NULL,
  article      text,
  external_code text,                        -- xlsx_id (код 1С)
  price        numeric(14,2),
  qty          numeric(14,3),
  in_stock     boolean DEFAULT false,
  source       text DEFAULT 'legacy',       -- legacy | price (пересчёт из прайсов)
  updated_at   timestamptz DEFAULT now()
);
CREATE INDEX ix_offers_product ON offers(product_id);
CREATE UNIQUE INDEX ux_offers_prod_sup ON offers(product_id, supplier_id) WHERE source='price';

-- ============================================================================
-- Клиенты и заказы (стабы — детализируем на след. этапе)
-- ============================================================================

CREATE TABLE customers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id     bigint UNIQUE,
  kind          text CHECK (kind IN ('person','legal')) DEFAULT 'person',
  name          text,
  phone         text,
  email         text,
  address       text,
  inn           text, kpp text, bank text, bik text,
  rschet        text, korschet text, org_name text,
  code_1c       text,                        -- код контрагента в 1С
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE orders (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  bigint REFERENCES customers(id) ON DELETE SET NULL,
  status       text DEFAULT 'new',
  total        numeric(14,2),
  channel      text,                          -- web | telegram | whatsapp | max
  order_1c_id  text,                          -- id документа в 1С:УНФ
  created_at   timestamptz DEFAULT now()
);

CREATE TABLE order_items (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    bigint REFERENCES orders(id) ON DELETE CASCADE,
  product_id  bigint REFERENCES products(id) ON DELETE SET NULL,
  article     text,
  name        text,
  qty         numeric(14,3),
  price       numeric(14,2)
);

-- Платежи физлиц (эквайринг ЮKassa/Т-Банк)
CREATE TABLE payments (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     bigint REFERENCES orders(id) ON DELETE CASCADE,
  provider     text,
  external_id  text,
  amount       numeric(14,2),
  currency     text DEFAULT 'RUB',
  status       text DEFAULT 'pending',       -- pending | succeeded | canceled
  confirmation_url text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);
CREATE INDEX ix_payments_order ON payments(order_id);
CREATE INDEX ix_payments_external ON payments(external_id);

-- Документы 1С:УНФ (Заказ/Счёт/УПД) + печатные формы + статус ЭДО Диадок
CREATE TABLE documents (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    bigint REFERENCES orders(id) ON DELETE CASCADE,
  kind        text NOT NULL,                 -- order | invoice | upd | waybill
  unf_ref     text,                          -- GUID/ref документа в 1С
  unf_number  text,
  pf_pdf      bytea,                          -- печатная форма (PDF), полученная из 1С
  status      text DEFAULT 'created',
  edo_status  text,                           -- статус в Диадок
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX ix_documents_order ON documents(order_id);

-- ============================================================================
-- Подписки «сообщить о поступлении» (из legacy it_b_notify)
-- ============================================================================
-- Клиент подписывается на товар, которого нет в наличии; когда по товару
-- появляется offer с in_stock — уходит письмо и подписка закрывается.
CREATE TABLE stock_alerts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint REFERENCES products(id) ON DELETE CASCADE,
  email       text NOT NULL,
  name        text,
  phone       text,
  notified_at timestamptz,                    -- NULL = ждёт поступления
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX ix_stock_alerts_pending ON stock_alerts(product_id) WHERE notified_at IS NULL;
-- Один активный запрос на пару (товар, почта); после отправки можно подписаться снова.
CREATE UNIQUE INDEX ux_stock_alerts_active
  ON stock_alerts(product_id, lower(email)) WHERE notified_at IS NULL;

-- ============================================================================
-- Метаданные миграции
-- ============================================================================
CREATE TABLE etl_runs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz DEFAULT now(),
  finished_at timestamptz,
  stats      jsonb
);
