"""Прямая интеграция с 1С:УНФ (БЕЗ файлового обмена).

Транспорт:
  * OData стандартного интерфейса 1С — чтение справочников/остатков и создание документов;
  * HTTP-сервисы расширения конфигурации — операции, которых нет в OData
    (проведение документа, получение печатной формы ПФ в PDF).

Всё конфигурируется через env. Без UNF_BASE_URL коннектор работает в DRY-RUN:
возвращает синтетические ссылки/ПФ, чтобы поток заказ→счёт→ПФ тестировался локально.
При появлении реальных доступов те же вызовы уходят в боевую УНФ.
"""
import os
import uuid
import httpx
from . import db

BASE_URL = os.environ.get("UNF_BASE_URL", "").rstrip("/")
USER = os.environ.get("UNF_USER", "")
PASSWORD = os.environ.get("UNF_PASSWORD", "")
ODATA_PATH = os.environ.get("UNF_ODATA_PATH", "/odata/standard.odata")
HS_ROOT = os.environ.get("UNF_HTTP_SERVICE_ROOT", "/hs/specinter")  # корень HTTP-сервисов расширения
TIMEOUT = float(os.environ.get("UNF_TIMEOUT", "30"))

# Имена сущностей OData (настраиваются под конкретную конфигурацию УНФ)
E_ORDER = os.environ.get("UNF_ENTITY_ORDER", "Document_ЗаказПокупателя")
E_INVOICE = os.environ.get("UNF_ENTITY_INVOICE", "Document_СчетНаОплатуПокупателю")
E_COUNTERPARTY = os.environ.get("UNF_ENTITY_COUNTERPARTY", "Catalog_Контрагенты")

DRY_RUN = not bool(BASE_URL and USER and PASSWORD)

MIGRATION = """
CREATE TABLE IF NOT EXISTS documents (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    bigint REFERENCES orders(id) ON DELETE CASCADE,
  kind        text NOT NULL,                 -- order | invoice | upd | waybill
  unf_ref     text,                          -- GUID/ref документа в 1С
  unf_number  text,                          -- номер документа
  pf_pdf      bytea,                         -- печатная форма (PDF)
  status      text DEFAULT 'created',
  edo_status  text,                          -- статус в Диадок (заполняется ЭДО-модулем)
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_documents_order ON documents(order_id);
"""

# Минимальный валидный PDF-заглушка для DRY-RUN (реальная ПФ приходит из HTTP-сервиса 1С).
_STUB_PDF = (
    b"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
    b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
    b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 120]/Contents 4 0 R"
    b"/Resources<</Font<</F1 5 0 R>>>>>>endobj\n"
    b"4 0 obj<</Length 66>>stream\nBT /F1 14 Tf 20 60 Td (SPECINTER: schet (DRY-RUN)) Tj ET\nendstream endobj\n"
    b"5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n"
    b"trailer<</Root 1 0 R>>\n%%EOF"
)


async def ensure_migrated():
    async with db.pool.connection() as conn:
        await conn.execute(MIGRATION)


def _client() -> httpx.AsyncClient:
    return httpx.AsyncClient(base_url=BASE_URL, auth=(USER, PASSWORD), timeout=TIMEOUT,
                             headers={"Accept": "application/json"})


async def status() -> dict:
    if DRY_RUN:
        return {"configured": False, "mode": "dry-run",
                "hint": "заполните UNF_BASE_URL/UNF_USER/UNF_PASSWORD в .env"}
    try:
        async with _client() as c:
            r = await c.get(f"{ODATA_PATH}/$metadata")
            return {"configured": True, "mode": "live", "odata_status": r.status_code}
    except Exception as e:
        return {"configured": True, "mode": "live", "error": str(e)}


async def upsert_counterparty(customer: dict) -> str:
    """Возвращает Ref_Key контрагента в 1С (создаёт при отсутствии)."""
    if DRY_RUN:
        return f"dry-cp-{uuid.uuid4()}"
    payload = {
        "Description": customer.get("org_name") or customer.get("name"),
        "ИНН": customer.get("inn") or "",
        "КПП": customer.get("kpp") or "",
    }
    async with _client() as c:
        r = await c.post(f"{ODATA_PATH}/{E_COUNTERPARTY}", json=payload)
        r.raise_for_status()
        return r.json().get("Ref_Key")


async def create_customer_order(order: dict, items: list[dict], cp_ref: str) -> dict:
    """Создаёт Заказ покупателя в УНФ. Возвращает {ref, number}."""
    if DRY_RUN:
        return {"ref": f"dry-order-{uuid.uuid4()}", "number": f"ДЕМО-{order['id']}"}
    payload = {
        "Контрагент_Key": cp_ref,
        "Комментарий": order.get("comment", ""),
        "Товары": [
            {"Номенклатура": it["article"], "Количество": it["qty"], "Цена": it["price"]}
            for it in items
        ],
    }
    async with _client() as c:
        r = await c.post(f"{ODATA_PATH}/{E_ORDER}?$expand=Товары", json=payload)
        r.raise_for_status()
        d = r.json()
        return {"ref": d.get("Ref_Key"), "number": d.get("Number")}


async def create_invoice(order: dict, order_ref: str) -> dict:
    """Создаёт Счёт на оплату на основании заказа. Возвращает {ref, number}."""
    if DRY_RUN:
        return {"ref": f"dry-invoice-{uuid.uuid4()}", "number": f"СЧ-{order['id']}"}
    payload = {"ДокументОснование": order_ref}
    async with _client() as c:
        r = await c.post(f"{ODATA_PATH}/{E_INVOICE}", json=payload)
        r.raise_for_status()
        d = r.json()
        return {"ref": d.get("Ref_Key"), "number": d.get("Number")}


async def get_printed_form(doc_ref: str, form: str = "СчетНаОплату") -> bytes:
    """Печатная форма (PDF) через HTTP-сервис расширения конфигурации 1С."""
    if DRY_RUN:
        return _STUB_PDF
    async with _client() as c:
        r = await c.get(f"{HS_ROOT}/print", params={"ref": doc_ref, "form": form},
                        headers={"Accept": "application/pdf"})
        r.raise_for_status()
        return r.content


async def get_stock(article: str) -> dict:
    """Остатки по номенклатуре напрямую из УНФ (для сверки наличия)."""
    if DRY_RUN:
        return {"article": article, "stock": None, "mode": "dry-run"}
    async with _client() as c:
        r = await c.get(f"{HS_ROOT}/stock", params={"article": article})
        r.raise_for_status()
        return r.json()
