"""Заявки на подбор (RFQ): если позиции нет в каталоге — не теряем клиента,
а фиксируем заявку. Источник — витрина (пустой поиск) или бот."""
from fastapi import APIRouter
from pydantic import BaseModel
from .. import db

router = APIRouter(prefix="/api", tags=["RFQ"])

MIGRATION = """
CREATE TABLE IF NOT EXISTS quote_requests (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query      text,                 -- искомый артикул/название
  name       text,
  phone      text,
  email      text,
  comment    text,
  channel    text DEFAULT 'web',
  status     text DEFAULT 'new',   -- new | processing | quoted | closed
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_quote_status ON quote_requests(status);
"""


async def ensure_migrated():
    async with db.pool.connection() as conn:
        await conn.execute(MIGRATION)


class QuoteIn(BaseModel):
    query: str
    name: str
    phone: str
    email: str | None = None
    comment: str | None = None
    channel: str = "web"


@router.post("/quote-requests")
async def create_quote(q: QuoteIn):
    await ensure_migrated()
    row = await db.fetchone(
        """INSERT INTO quote_requests (query, name, phone, email, comment, channel)
           VALUES (%s,%s,%s,%s,%s,%s) RETURNING id""",
        (q.query, q.name, q.phone, q.email, q.comment, q.channel))
    return {"id": row["id"], "status": "new",
            "message": "Заявка принята. Подберём и свяжемся с вами."}


@router.get("/admin/quote-requests")
async def list_quotes(status: str | None = None, limit: int = 100):
    if status:
        return await db.fetch(
            "SELECT * FROM quote_requests WHERE status=%s ORDER BY created_at DESC LIMIT %s",
            (status, limit))
    return await db.fetch(
        "SELECT * FROM quote_requests ORDER BY created_at DESC LIMIT %s", (limit,))
