"""Заявки на подбор / запрос цены (RFQ). Источник — витрина (кнопка «Запросить»,
позиции без цены) или бот. Автообработка формирует ответ клиенту (наличие/цена/аналоги)
БЕЗ участия человека. Всё взаимодействие — через API; прямого доступа к БД снаружи нет."""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from .. import db

router = APIRouter(prefix="/api", tags=["RFQ"])

MIGRATION = """
CREATE TABLE IF NOT EXISTS quote_requests (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query      text,                 -- искомый артикул/название (свободный текст)
  name       text,
  phone      text,
  email      text,
  comment    text,
  channel    text DEFAULT 'web',   -- web | telegram | whatsapp | max | ...
  contact_ref text,                -- id чата/канала для обратной связи ботом
  status     text DEFAULT 'new',   -- new | processing | quoted | closed
  response   text,                 -- сводный ответ клиенту (итог автообработки)
  processed_at timestamptz,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_quote_status ON quote_requests(status);
ALTER TABLE quote_requests ADD COLUMN IF NOT EXISTS contact_ref text;
ALTER TABLE quote_requests ADD COLUMN IF NOT EXISTS response text;
ALTER TABLE quote_requests ADD COLUMN IF NOT EXISTS processed_at timestamptz;

CREATE TABLE IF NOT EXISTS quote_items (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id     bigint REFERENCES quote_requests(id) ON DELETE CASCADE,
  product_id   bigint,
  article      text,
  name         text,
  qty          numeric(14,3) DEFAULT 1,
  found_price  numeric(14,2),       -- результат автообработки (розница)
  availability text,                -- в наличии | под заказ | не найдено
  eta_days     int,
  note         text
);
CREATE INDEX IF NOT EXISTS ix_quote_items_quote ON quote_items(quote_id);

-- Канал связи клиента (для обратной связи ботом): telegram|whatsapp|max|email|phone
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_channel text;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_ref text;
"""


async def ensure_migrated():
    async with db.pool.connection() as conn:
        await conn.execute(MIGRATION)


class QuoteItemIn(BaseModel):
    product_id: int | None = None
    article: str | None = None
    name: str | None = None
    qty: float = 1


class QuoteIn(BaseModel):
    query: str | None = None
    name: str
    phone: str
    email: str | None = None
    comment: str | None = None
    channel: str = "web"
    contact_ref: str | None = None
    items: list[QuoteItemIn] = []
    auto_process: bool = True          # бот обрабатывает сразу, без человека


@router.post("/quote-requests")
async def create_quote(q: QuoteIn):
    await ensure_migrated()
    row = await db.fetchone(
        """INSERT INTO quote_requests (query, name, phone, email, comment, channel, contact_ref)
           VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING id""",
        (q.query, q.name, q.phone, q.email, q.comment, q.channel, q.contact_ref))
    qid = row["id"]
    for it in q.items:
        await db.fetchone(
            """INSERT INTO quote_items (quote_id, product_id, article, name, qty)
               VALUES (%s,%s,%s,%s,%s) RETURNING id""",
            (qid, it.product_id, it.article, it.name, it.qty))
    result = {"id": qid, "status": "new", "message": "Заявка принята. Подбираем…"}
    if q.auto_process:
        result = {**result, **(await _process(qid))}
    return result


async def _process(qid: int) -> dict:
    """Автообработка: по каждой позиции берём актуальные наличие/цену/срок/аналоги
    и формируем ответ клиенту. Возвращает сводку + статус."""
    q = await db.fetchone("SELECT * FROM quote_requests WHERE id=%s", (qid,))
    if not q:
        raise HTTPException(404, "заявка не найдена")
    items = await db.fetch("SELECT * FROM quote_items WHERE quote_id=%s ORDER BY id", (qid,))
    lines, any_found = [], False

    async def _resolve(product_id, article):
        """Находит товар (по id или артикулу) и его лучшую розничную цену/наличие."""
        pid = product_id
        if not pid and article:
            r = await db.fetch(
                "SELECT id FROM products WHERE normalized_article=norm_article(%s) AND visible LIMIT 1",
                (article,))
            pid = r[0]["id"] if r else None
        if not pid:
            return None
        p = await db.fetchone("SELECT id, manufacturer_article, name FROM products WHERE id=%s", (pid,))
        best = await db.fetchone(
            """SELECT MIN(price) FILTER (WHERE price IS NOT NULL) AS price,
                      BOOL_OR(in_stock) AS in_stock
               FROM offers WHERE product_id=%s""", (pid,))
        eta = await db.fetchone(
            """SELECT MIN(s.delivery_days) AS d FROM offers o JOIN suppliers s ON s.id=o.supplier_id
               WHERE o.product_id=%s AND o.source='price'""", (pid,))
        return {"product": p, "price": best and best["price"], "in_stock": best and best["in_stock"],
                "eta": eta and eta["d"]}

    # позиции заявки
    if items:
        for it in items:
            res = await _resolve(it["product_id"], it["article"])
            if res and res["price"] is not None:
                any_found = True
                avail = "в наличии" if res["in_stock"] else "под заказ"
                eta_txt = f", срок ~{res['eta']} раб. дн." if res["eta"] else ""
                await db.fetchone(
                    """UPDATE quote_items SET found_price=%s, availability=%s, eta_days=%s
                       WHERE id=%s RETURNING id""",
                    (round(res["price"]), avail, res["eta"], it["id"]))
                lines.append(f"• {res['product']['manufacturer_article']} "
                             f"{res['product']['name']} — {round(res['price'])} ₽ "
                             f"({avail}{eta_txt}), кол-во {int(it['qty'])}")
            else:
                await db.fetchone(
                    "UPDATE quote_items SET availability='не найдено' WHERE id=%s RETURNING id",
                    (it["id"],))
                nm = it["article"] or it["name"] or "позиция"
                lines.append(f"• {nm} — уточняется, подберём аналог")
    # свободный текст
    elif q["query"]:
        res = await _resolve(None, q["query"])
        if res and res["price"] is not None:
            any_found = True
            avail = "в наличии" if res["in_stock"] else "под заказ"
            lines.append(f"• {res['product']['manufacturer_article']} "
                         f"{res['product']['name']} — {round(res['price'])} ₽ ({avail})")
        else:
            lines.append(f"• «{q['query']}» — в каталоге не нашли, подберём по запросу")

    header = ("Готова оценка по вашему запросу:" if any_found
              else "Приняли запрос — подбираем и уточняем цену:")
    response = header + "\n" + "\n".join(lines)
    status = "quoted" if any_found else "processing"
    await db.fetchone(
        "UPDATE quote_requests SET status=%s, response=%s, processed_at=now() WHERE id=%s RETURNING id",
        (status, response, qid))
    return {"status": status, "response": response, "found": any_found}


@router.post("/quote-requests/{qid}/process")
async def process_quote(qid: int):
    """Ручной/ботовый повторный прогон автообработки заявки."""
    await ensure_migrated()
    return await _process(qid)


@router.get("/quote-requests/{qid}")
async def get_quote(qid: int):
    q = await db.fetchone("SELECT * FROM quote_requests WHERE id=%s", (qid,))
    if not q:
        raise HTTPException(404, "заявка не найдена")
    q["items"] = await db.fetch("SELECT * FROM quote_items WHERE quote_id=%s ORDER BY id", (qid,))
    return q


@router.get("/admin/quote-requests")
async def list_quotes(status: str | None = None, limit: int = 100):
    if status:
        return await db.fetch(
            "SELECT * FROM quote_requests WHERE status=%s ORDER BY created_at DESC LIMIT %s",
            (status, limit))
    return await db.fetch(
        "SELECT * FROM quote_requests ORDER BY created_at DESC LIMIT %s", (limit,))
