"""Приём платежей физлиц. Провайдер-агностично: ЮKassa или Т-Банк (карты + СБП).
Без кредов — DRY-RUN: возвращает mock-ссылку оплаты, статус можно эмулировать вебхуком.
Юрлицам оплата не через эквайринг, а по счёту из 1С:УНФ (см. unf.py)."""
import hashlib
import os
import uuid
import httpx
from . import db

PROVIDER = os.environ.get("PAY_PROVIDER", "yookassa")   # yookassa | tinkoff
RETURN_URL = os.environ.get("PAY_RETURN_URL", "http://localhost:3000/order/success")

YK_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "")
YK_SECRET = os.environ.get("YOOKASSA_SECRET_KEY", "")
TB_TERMINAL = os.environ.get("TINKOFF_TERMINAL_KEY", "")
TB_PASSWORD = os.environ.get("TINKOFF_PASSWORD", "")

_yk_ready = bool(YK_SHOP_ID and YK_SECRET)
_tb_ready = bool(TB_TERMINAL and TB_PASSWORD)
DRY_RUN = not (_yk_ready if PROVIDER == "yookassa" else _tb_ready)

MIGRATION = """
CREATE TABLE IF NOT EXISTS payments (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     bigint REFERENCES orders(id) ON DELETE CASCADE,
  provider     text,
  external_id  text,
  amount       numeric(14,2),
  currency     text DEFAULT 'RUB',
  status       text DEFAULT 'pending',    -- pending | succeeded | canceled
  confirmation_url text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_payments_order ON payments(order_id);
CREATE INDEX IF NOT EXISTS ix_payments_external ON payments(external_id);
"""


async def ensure_migrated():
    async with db.pool.connection() as conn:
        await conn.execute(MIGRATION)


async def create_payment(order_id: int, amount: float, description: str) -> dict:
    """Создаёт платёж у провайдера, сохраняет и возвращает ссылку оплаты."""
    await ensure_migrated()
    if DRY_RUN:
        ext = f"dry-pay-{uuid.uuid4()}"
        url = f"{RETURN_URL}?mock_payment={ext}"
        status = "pending"
    elif PROVIDER == "yookassa":
        ext, url, status = await _yookassa_create(order_id, amount, description)
    else:
        ext, url, status = await _tinkoff_create(order_id, amount, description)

    row = await db.fetchone(
        """INSERT INTO payments (order_id, provider, external_id, amount, status, confirmation_url)
           VALUES (%s,%s,%s,%s,%s,%s) RETURNING id""",
        (order_id, "dry-run" if DRY_RUN else PROVIDER, ext, amount, status, url))
    return {"payment_id": row["id"], "external_id": ext, "confirmation_url": url,
            "status": status, "mode": "dry-run" if DRY_RUN else PROVIDER}


async def _yookassa_create(order_id, amount, description):
    body = {
        "amount": {"value": f"{amount:.2f}", "currency": "RUB"},
        "capture": True,
        "confirmation": {"type": "redirect", "return_url": RETURN_URL},
        "description": description,
        "metadata": {"order_id": order_id},
    }
    async with httpx.AsyncClient(timeout=30) as c:
        r = await c.post("https://api.yookassa.ru/v3/payments", json=body,
                         auth=(YK_SHOP_ID, YK_SECRET),
                         headers={"Idempotence-Key": str(uuid.uuid4())})
        r.raise_for_status()
        d = r.json()
        return d["id"], d["confirmation"]["confirmation_url"], d["status"]


def _tb_token(params: dict) -> str:
    params = {**params, "Password": TB_PASSWORD}
    concat = "".join(str(params[k]) for k in sorted(params))
    return hashlib.sha256(concat.encode()).hexdigest()


async def _tinkoff_create(order_id, amount, description):
    payload = {
        "TerminalKey": TB_TERMINAL,
        "Amount": int(round(amount * 100)),   # в копейках
        "OrderId": str(order_id),
        "Description": description,
    }
    payload["Token"] = _tb_token(payload)
    async with httpx.AsyncClient(timeout=30) as c:
        r = await c.post("https://securepay.tinkoff.ru/v2/Init", json=payload)
        r.raise_for_status()
        d = r.json()
        if not d.get("Success"):
            raise RuntimeError(d.get("Message", "tinkoff init failed"))
        return str(d["PaymentId"]), d["PaymentURL"], "pending"


async def set_status(external_id: str, status: str):
    await db.fetchone(
        "UPDATE payments SET status=%s, updated_at=now() WHERE external_id=%s RETURNING id",
        (status, external_id))
    if status == "succeeded":
        await db.fetchone(
            """UPDATE orders SET status='paid' WHERE id=(
                 SELECT order_id FROM payments WHERE external_id=%s) RETURNING id""",
            (external_id,))
